### ISSUE TITLE
Debug folder should not be uploaded

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [RISCV-on-Microsemi-FPGA/LiteOS#2]
https://github.com/RISCV-on-Microsemi-FPGA/LiteOS/tree/master/miv-rv32im-liteos-port-test/Debug

**Comment by CLappin** [comment]
I'll remove the debug folder on Monday.

**Comment by TommyMurphyTM1234** [comment]
The Debug folder is there again - I think the folder needs a .gitignore like this:

https://github.com/RISCV-on-Microsemi-FPGA/LiteOS/blob/master/miv-rv32im-wifi-udp-liteos/.gitignore

**Comment by CLappin** [comment]
Debug folder removed.
Will check use git ignore in future.

**Comment by kevinscully100** [comment]
.gitignore added to both projects to stop Debug folder upload
